insert into equipment (name, equipment_Type_Id) values ('Apple CarPlay', 1);
insert into equipment (name, equipment_Type_Id) values ('Android Auto', 1);
insert into equipment (name, equipment_Type_Id) values ('Interfejs Bluetooth', 1);
insert into equipment (name, equipment_Type_Id) values ('Radio', 1);
insert into equipment (name, equipment_Type_Id) values ('Zestaw głośnomówiący', 1);
insert into equipment (name, equipment_Type_Id) values ('Gniazdo USB', 1);
insert into equipment (name, equipment_Type_Id) values ('System nagłośnienia', 1);
insert into equipment (name, equipment_Type_Id) values ('Ekran dotykowy', 1);
insert into equipment (name, equipment_Type_Id) values ('System nawigacji satelitarnej', 1);
insert into equipment (name, equipment_Type_Id) values ('Sterowanie funkcjami pojazdu za pomocą głosu', 1);
insert into equipment (name, equipment_Type_Id) values ('Dostęp do internetu', 1);


insert into equipment (name, equipment_Type_Id) values ('Klimatyzacja automatyczna, dwustrefowa', 2);
insert into equipment (name, equipment_Type_Id) values ('Dach materiałowy', 2);
insert into equipment (name, equipment_Type_Id) values ('Dach panoramiczny', 2);
insert into equipment (name, equipment_Type_Id) values ('Tapicerka skórzana', 2);
insert into equipment (name, equipment_Type_Id) values ('Klimatyzacja dla pasażerów z tyłu', 2);
insert into equipment (name, equipment_Type_Id) values ('Elektrycznie ustawiany fotel kierowcy', 2);
insert into equipment (name, equipment_Type_Id) values ('Elektrycznie ustawiany fotel pasażera', 2);
insert into equipment (name, equipment_Type_Id) values ('Podgrzewany fotel kierowcy', 2);
insert into equipment (name, equipment_Type_Id) values ('Podgrzewany fotel pasażera', 2);
insert into equipment (name, equipment_Type_Id) values ('Siedzenie z pamięcią ustawienia', 2);
insert into equipment (name, equipment_Type_Id) values ('Ogrzewane siedzenia tylne', 2);
insert into equipment (name, equipment_Type_Id) values ('Kierownica ogrzewana', 2);
insert into equipment (name, equipment_Type_Id) values ('Elektryczne szyby przednie', 2);
insert into equipment (name, equipment_Type_Id) values ('Elektryczne szyby tylne', 2);
insert into equipment (name, equipment_Type_Id) values ('Wycieraczki', 2);
insert into equipment (name, equipment_Type_Id) values ('Dach otwierany elektrycznie', 2);
insert into equipment (name, equipment_Type_Id) values ('Kierownica wielofunkcyjna', 2);
insert into equipment (name, equipment_Type_Id) values ('Kierownica ze sterowaniem radia', 2);
insert into equipment (name, equipment_Type_Id) values ('Kierownica skórzana', 2);
insert into equipment (name, equipment_Type_Id) values ('Podłokietniki - przód', 2);
insert into equipment (name, equipment_Type_Id) values ('Podłokietniki - tył', 2);
insert into equipment (name, equipment_Type_Id) values ('Fotele przednie z funkcje masażu', 2);
insert into equipment (name, equipment_Type_Id) values ('Dźwignia zmiany biegów wykończona skórą', 2);
insert into equipment (name, equipment_Type_Id) values ('Przyciemniane tylne szyby', 2);
insert into equipment (name, equipment_Type_Id) values ('Czujnik deszczu', 2);
insert into equipment (name, equipment_Type_Id) values ('Keyless entry', 2);

insert into equipment (name, equipment_Type_Id) values ('Tempomat adaptacyjny ACC', 3);
insert into equipment (name, equipment_Type_Id) values ('Lampy przednie w technologii LED', 3);
insert into equipment (name, equipment_Type_Id) values ('Kontrola odległości z przodu (przy parkowaniu)', 3);
insert into equipment (name, equipment_Type_Id) values ('Kontrola odległości z tyłu (przy parkowaniu)', 3);
insert into equipment (name, equipment_Type_Id) values ('Park Assistant - asystent parkowania', 3);
insert into equipment (name, equipment_Type_Id) values ('Kamera parkowania tył', 3);
insert into equipment (name, equipment_Type_Id) values ('Lusterka boczne ustawiane elektrycznie', 3);
insert into equipment (name, equipment_Type_Id) values ('Podgrzewane lusterka boczne', 3);
insert into equipment (name, equipment_Type_Id) values ('Lusterka boczne składane elektrycznie', 3);
insert into equipment (name, equipment_Type_Id) values ('Asystent (czujnik) martwego pola', 3);
insert into equipment (name, equipment_Type_Id) values ('Aktywny asystent zmiany pasa ruchu', 3);
insert into equipment (name, equipment_Type_Id) values ('Lane assist - kontrola zmiany pasa ruchu', 3);
insert into equipment (name, equipment_Type_Id) values ('Ogranicznik prędkości', 3);
insert into equipment (name, equipment_Type_Id) values ('Asystent hamowania - Brake Assist', 3);
insert into equipment (name, equipment_Type_Id) values ('Kontrola trakcji', 3);
insert into equipment (name, equipment_Type_Id) values ('Asystent świateł drogowych', 3);
insert into equipment (name, equipment_Type_Id) values ('Oświetlenie adaptacyjne', 3);
insert into equipment (name, equipment_Type_Id) values ('Dynamiczne światła doświetlające zakręty', 3);
insert into equipment (name, equipment_Type_Id) values ('Czujnik zmierzchu', 3);
insert into equipment (name, equipment_Type_Id) values ('Lampy doświetlające zakręt', 3);
insert into equipment (name, equipment_Type_Id) values ('Światła do jazdy dziennej', 3);
insert into equipment (name, equipment_Type_Id) values ('Światła do jazdy dziennej diodowe LED', 3);
insert into equipment (name, equipment_Type_Id) values ('Lampy przeciwmgielne', 3);
insert into equipment (name, equipment_Type_Id) values ('System Start/Stop', 3);
insert into equipment (name, equipment_Type_Id) values ('Elektroniczna kontrola ciśnienia w oponach', 3);
insert into equipment (name, equipment_Type_Id) values ('Elektryczny hamulec postojowy', 3);
insert into equipment (name, equipment_Type_Id) values ('Wspomaganie kierownicy', 3);
insert into equipment (name, equipment_Type_Id) values ('Blokada mechanizmu różnicowego', 3);
insert into equipment (name, equipment_Type_Id) values ('Tempomat', 3);
insert into equipment (name, equipment_Type_Id) values ('Kamera panoramiczna 360', 3);
insert into equipment (name, equipment_Type_Id) values ('Lampy tylne w technologii LED', 3);

insert into equipment (name, equipment_Type_Id) values ('Felgi aluminiowe 19', 4);
insert into equipment (name, equipment_Type_Id) values ('Zawieszenie regulowane', 4);
insert into equipment (name, equipment_Type_Id) values ('Felgi aluminiowe 17', 4);
insert into equipment (name, equipment_Type_Id) values ('Opony letnie', 4);
insert into equipment (name, equipment_Type_Id) values ('Zawieszenie sportowe', 4);
insert into equipment (name, equipment_Type_Id) values ('Felgi aluminiowe 18', 4);
insert into equipment (name, equipment_Type_Id) values ('Opony zimowe', 4);

insert into equipment (name, equipment_Type_Id) values ('ABS', 5);
insert into equipment (name, equipment_Type_Id) values ('ESP', 5);
insert into equipment (name, equipment_Type_Id) values ('Aktywny asystent hamowania awaryjnego', 5);
insert into equipment (name, equipment_Type_Id) values ('System ostrzegający o możliwej kolizji', 5);
insert into equipment (name, equipment_Type_Id) values ('System minimalizujący skutki kolizji', 5);
insert into equipment (name, equipment_Type_Id) values ('Poduszka powietrzna kierowcy', 5);
insert into equipment (name, equipment_Type_Id) values ('Poduszka powietrzna pasażera', 5);
insert into equipment (name, equipment_Type_Id) values ('Poduszka kolan kierowcy', 5);
insert into equipment (name, equipment_Type_Id) values ('Poduszka kolan pasażera', 5);
insert into equipment (name, equipment_Type_Id) values ('Kurtyny powietrzne - przód', 5);
insert into equipment (name, equipment_Type_Id) values ('Boczne poduszki powietrzne - przód', 5);
insert into equipment (name, equipment_Type_Id) values ('Isofix (punkty mocowania fotelika dziecięcego)', 5);
insert into equipment (name, equipment_Type_Id) values ('Kurtyny powietrzne - tył', 5);
insert into equipment (name, equipment_Type_Id) values ('Boczna poduszka powietrzna kierowcy', 5);
insert into equipment (name, equipment_Type_Id) values ('Asystent pasa ruchu', 5);
insert into equipment (name, equipment_Type_Id) values ('Alarm ruchu poprzecznego z tyłu pojazdu', 5);


insert into equipment (name, equipment_Type_Id) values ('System odzyskiwania energii', 6);
insert into equipment (name, equipment_Type_Id) values ('Funkcja szybkiego ładowania', 6);
insert into equipment (name, equipment_Type_Id) values ('Kabel do ładowania', 6);

