apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oto-auto-db-replica
spec:
  serviceName: "db-replica-svc"
  selector:
    matchLabels:
      app: oto-auto-db
      role: replica
  replicas: 2
  template:
    metadata:
      labels:
        app: oto-auto-db
        role: replica
    spec:
      initContainers:
          - name: init
            image: postgres:15.0
            command: [ "bash", "-c" ]
            args:
            - |+
              if [ -z "$(ls -A /replica/data)" ]; then
                pg_basebackup -h db-master-svc -U replica_user -D /replica/data -Fp -Xs -R
              fi
              
            volumeMounts:
            - name: oto-auto-db-replica
              mountPath: /replica/data
              readOnly: false
      containers:
        - name: oto-auto-db-replica
          image: postgres:15.0
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_USER
              value: dominik
            - name: POSTGRES_PASSWORD
              value: '12345'
            - name: POSTGRES_DB
              value: oto_auto
            - name: PGDATA
              value: "/replica/data"
          ports: 
            - containerPort: 5432
          volumeMounts:
            - name: oto-auto-db-replica
              mountPath: /replica/data
              readOnly: false
            - name: oto-auto-db-replica
              mountPath:  /replica/config
            - name: oto-auto-db-replica
              mountPath:  /replica/archive
      volumes:
        - name: oto-auto-db-replica
          persistentVolumeClaim:
            claimName: volume-replica-claim