apiVersion: v1
kind: Service
metadata:
  name: db-master-svc
spec:
  selector:
    app: oto-auto-db
    role: master
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None


---

apiVersion: v1
kind: Service
metadata:
  name: db-replica-svc
spec:
  selector:
    app: oto-auto-db
    role: replica
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None 

  