apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oto-auto-db
spec:
  serviceName: oto-auto-db-service
  selector:
    matchLabels:
      app: oto-auto-db
  replicas: 3
  template:
    metadata:
      labels:
        app: oto-auto-db
    spec:
      containers:
        - name: oto-auto-db
          image: postgres:15.4
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_USER
              value: dominik
            - name: POSTGRES_PASSWORD
              value: 12345
            - name: POSTGRES_DB
              value: oto_auto
            - name: PGDATA
              value: /data/postgres
          ports: 
            - containerPort: 5432
          volumeMounts:
            - name: oto-auto-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: oto-auto-data
          persistentVolumeClaim:
            claimName: oto-auto-db-pvc
