apiVersion: v1
kind: PersistentVolume
metadata:
  name: oto-auto-db-pv
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oto-auto-db-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi