apiVersion: v1
kind: Pod
metadata:
  name: psql-client
spec:
  containers:
    - name: psql-client
      image: postgres:15.4
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 1000; done"]