version: '3.1'

services:
  postgres:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: dominik
      POSTGRES_PASSWORD: 12345
      PGDATA: /data/postgres
      POSTGRES_DB: oto_auto
    volumes:
      - postgres:/data/postgres
    ports:
      - "8090:5432"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
