version: '3.1'

services:
  angular_oto_auto:
    image: tloku/angular-oto-auto:1.0
    restart: always
    ports: 
      - "4200:80"

  react_oto_auto:
    image: tloku/react-oto-auto:1.0
    restart: always
    ports: 
      - "4300:80"

  vue_oto_auto:
    image: tloku/vue-oto-auto:1.0
    restart: always
    ports: 
      - "4400:80"

  postgres:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: dominik
      POSTGRES_PASSWORD: 12345
      PGDATA: /data/postgres
      POSTGRES_DB: oto_auto
    volumes:
      - postgres:/data/postgres
      - /app/SQL_Scripts:/var/SQL_Scripts
    ports:
      - "8090:5432"

  redis:
    image: redis:7.2.4
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass 12345
    volumes:
      - redis:/data/redis
    ports:
      - "6379:6379"

  server:
    image: tloku/oto-auto-server:1.0
    restart: always
    volumes:
      - /Cars_Dataset:/var/cars_dataset
    ports:
      - "5000:5000"

  cache_server:
    image: tloku/cache-server:1.0
    restart: always
    ports:
      - "3500:3500"
  

networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge
  cache_server:
    driver: bridge
  angular_oto_auto:
    driver: bridge

volumes:
  postgres:
  redis: