version: '3.1'

services:
  postgres:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: dominik
      POSTGRES_PASSWORD: 12345
      PGDATA: /data/postgres
      POSTGRES_DB: oto_auto
    volumes:
      - postgres:/data/postgres
      - D:\Studia\masters_thesis\Aplikacja\Deployment\Database\SQL_Scripts:/var/SQL_Scripts
      - D:\Studia\masters_thesis\Aplikacja\Deployment\Database\initdb.sh:/var/SQL_Scripts/initdb.sh
    ports:
      - "8090:5432"

  redis:
    image: redis:7.2.4
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass 12345
    volumes:
      - redis:/data/redis
    ports:
      - "6379:6379"

  server:
    image: tloku/oto-auto-server:1.0
    restart: always
    volumes:
      - D:\Studia\masters_thesis\Dodatki\car-images-dataset\Cars_Dataset:/var/cars_dataset
    ports:
      - "5252:5000"
  

networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge

volumes:
  postgres:
  redis: