apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hostpath
provisioner: docker.io/hostpath
reclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: oto-auto-db-pv-1
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/my_data/1"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: oto-auto-db-pv-2
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/my_data/2"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oto-auto-db-master-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  securityContext:
    fsGroup: 999

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oto-auto-db-replica-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi  
  securityContext:
    fsGroup: 999