apiVersion: v1
kind: ConfigMap
metadata:
  name: db-master-config
data:
  postgresql.conf: |+
    listen_addresses = '*'
    max_wal_senders = 3
    wal_level = replica

  pg_hba.conf: |+
    host replication replica_user oto-auto-db-replica-svc trust

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: db-replica-config
data:
  postgresql.conf: |+
    hot_standby = 'on'
    primary_conninfo = 'host=oto-auto-db-master-svc port=5432 user=replication_user password=12345'
