apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-master
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/customFolder"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-master-claim
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi